const SENDGRID_API_KEY = "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";

const PORT = 8086;

const HTTP_STATUS_CODES = {
    OK: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    INTERNAL_SERVER_ERROR: 500,
}

const NODE_ENVIRONMENTS = {
    DEVELOPMENT: "DEVELOPMENT",
    PRODUCTION: "PRODUCTION",
}

const NODE_ENVIRONMENT = NODE_ENVIRONMENTS.PRODUCTION;

module.exports = {
    SENDGRID_API_KEY,
    PORT,
    HTTP_STATUS_CODES,
    NODE_ENVIRONMENTS,
    NODE_ENVIRONMENT
}